# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-2'

menu:
- {name: 'Services',  url: 'services'}
- {name: 'Featured Projects',  url: 'projects'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link:   'https://www.facebook.com/scottishgardendesigner'}
- {icon: 'instagram', link:  'https://instagram.com/blackwood_gardens'}
- {icon: 'pinterest', link:  'https://www.pinterest.co.uk/ablackwood0787'}
- {icon: 'envelope', link:   'mailto:blackwoodgardens@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: ''
  previous_page: ''

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'
hide_post_date: 'true'
post_date_prefix:  ''
